Ticket 31
hatchways/team-cheesesteak pull request #39
Opened 2021-02-11 14:20 UTC by kipp0

.gitignore update

2021-02-11 17:26 UTC, sina-jamshidi requested changes

2021-02-11 17:26 UTC, sina-jamshidi commented on client/src/component/Auth.js
> +import React, { Component } from "react";
you should be using a linter to make the code more uniform

2021-02-11 17:26 UTC, sina-jamshidi commented on client/src/component/Auth.js
> +export default class Auth extends Component {
we will be using functional components with hooks as per [official React recommendations](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both).

2021-02-11 17:26 UTC, sina-jamshidi commented on client/src/component/TopBar.js
> +import React from 'react';
`import React, {useState} from 'react'`

2021-02-11 17:26 UTC, sina-jamshidi commented on client/src/component/TopBar.js
> +	const [auth, setAuth] = React.useState(user);
see note above. No need to keep doing `React.useState()`.

2021-02-11 17:26 UTC, sina-jamshidi commented on client/src/component/TopBar.js
> +	const [auth, setAuth] = React.useState(user);
Also it is an antipattern to duplicate a prop with local state. You can just access the prop, there's no need for the `auth` state here.

2021-02-11 17:26 UTC, sina-jamshidi commented on client/src/component/TopBar.js
> +	});
Let's not mix in so many different things together. KEep the states together, declare variables somewhere else

2021-02-11 17:26 UTC, sina-jamshidi commented on client/src/component/TopBar.js
> +	});
`state` is not a good name for this. It should be something like `[top, setTop]`.
We should not replicate `[state, setState]` from class components. Defeats the purpose of hooks.

2021-02-12 15:05 UTC, dproc96 reviewed
Hey, so just to clarify, the expectation for this task is to create a React Context to store authentication details and create a Navbar that matches the mocks. Looking at the card it does read a bit unclear, so I'm going to update that

Please also install prettier.io on your editor and run it on your files.

2021-02-12 15:05 UTC, dproc96 commented on client/src/component/Auth.js
> +export default function Auth(props) {
It would be much better to use React context to handle the logged in user https://reactjs.org/docs/context.html

2021-02-12 15:05 UTC, dproc96 commented on client/src/component/Auth.js
> +		// const url = ''
You can remove this commented out code, logic will be written as part of that task

2021-02-12 15:05 UTC, dproc96 commented on client/src/component/TopBar.js
> +import DragHandleIcon from '@material-ui/icons/DragHandle';
@material-ui/icons hasn't been installed so it crashes the application, you'll need to add that to the package.json if you want to use it

2021-02-12 15:05 UTC, dproc96 commented on client/src/component/TopBar.js
> +		if (event.type === 'keydown' && (event.key === 'Tab' || event.key === 'Shift')) {
I'm confused at the purpose of this conditional, it doesn't seem to do anything

2021-02-12 15:05 UTC, dproc96 commented on client/src/component/TopBar.js
> +						<Link to='/' className='logoname'>CHEF'S MENU</Link>
The links are displaying with underlines which doesn't look great, can you add textDecoration: none so these look better

2021-02-12 15:05 UTC, dproc96 commented on client/src/App.js
> +// import ChefPage from "./pages/Chef";
You can remove this commented out code

2021-02-18 15:53 UTC, kipp0 commented
This PR is Now Closed. Branch "ticket-18" handles the topbar pr requests

2021-02-18 20:22 UTC, closed without merging